apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.astronut.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.astronut.image.repository }}:{{ .Values.astronut.image.tag }}
        name: {{ .Values.astronut.app.name }}
        resources: {}
        readinessProbe:
          httpGet:
            path: {{ .Values.astronut.readiness.path }}
            port: {{ .Values.astronut.readiness.port }}
          initialDelaySeconds: {{ .Values.astronut.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.astronut.readiness.periodSeconds }}
        livenessProbe:
          httpGet:
            path: {{ .Values.astronut.liveness.path }}
            port: {{ .Values.astronut.liveness.port }}
          initialDelaySeconds: {{ .Values.astronut.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.astronut.liveness.periodSeconds }}
status: {}
