
{{ $appname := .Values.astronut.app.name}}
{{ $app := .Values.astronut}}
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ upper .Release.Name }}
  name: {{ upper .Release.Name }}
  app-name: {{ $appname }}
data: 
spec:
  sname: {{ default "spaceworld" .Values.astronut.name | upper | quote}}
  replicas: {{ default "3" .Values.astronut.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.astronut.image.repository }}:{{ .Values.astronut.image.tag }}
        name: {{- template "application"}}
        resources: {}
        {{- if .Values.astronut.readiness.enabled }}
        {{with .Values.astronut.readiness}}
        readinessProbe:
          httpGet:
            path: {{ .path }}
            port: {{ .port }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
        {{- end }}
        {{- end }}
        {{- if .Values.astronut.liveness.enabled }}
        {{with .Values.astronut.liveness}}
        livenessProbe:
          httpGet:
            path: {{ .path }}
            port: {{ .port }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          {{- end }}
        {{- end }}
status: {}
